blog/urls.py
from django.conf.urls import url, include
from django.views.generic import ListView, DetailView
from blog.models import Post

from . import views


app_name = 'blog'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^blog/(?P<pk>\d+)$', views.DetailView.as_view(), name='post'),
]

landoflei/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('blog.urls')),
    url(r'^members/', include('members.urls')),
    url(r'^publications/', include('publications.urls')),
    url(r'^projects/', include('projects.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.conf.urls import url

from . import views


app_name = 'members'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
]

projects/urls.py
from django.conf.urls import url

from . import views


app_name = 'projects'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

publications/urls.py
from django.conf.urls import url

from . import views

app_name = 'publications'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
]

blog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    picture = models.FileField(blank=True)
    published_date = models.DateTimeField(
        blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()


    def __str__(self):
        return self.title

members/models.py
from django.db import models

# Create your models here.
class Member(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    position = models.CharField(max_length=200)
    new_employer = models.CharField(max_length=200, blank=True)
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    research_interests = models.TextField()
    picture = models.FileField(blank=True)

    def __str__(self):
        return self.last_name + ', ' + self.first_name

projects/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=300)
    description = models.TextField()
    funding = models.CharField(max_length=200, blank=True)
    picture = models.FileField(blank=True)

    def __str__(self):
        return self.title

publications/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Publication(models.Model):
    citation = models.TextField()
    title = models.CharField(max_length=300)
    pub_date = models.DateField()

    def __str__(self):
        return self.title

blog/views.py
from django.views import generic
from .models import Post


class IndexView(generic.ListView):
    template_name = 'blog/index.html'

    def get_queryset(self):
        return Post.objects.order_by('-published_date')[:8]

class DetailView(generic.DetailView):
    model = Post
    template_name = 'blog/post.html'

members/views.py
from django.views import generic
from .models import Member


class IndexView(generic.ListView):
    template_name = 'members/index.html'

    def get_queryset(self):
        return Member.objects.order_by('start_date')

projects/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Project


def index(request):
    all_projects = Project.objects.all()
    context = {'all_projects' : all_projects}
    return render(request, 'projects/index.html', context)

publications/views.py
from django.views import generic
from .models import Publication


class IndexView(generic.ListView):
    template_name = 'publications/index.html'

    def get_queryset(self):
        return Publication.objects.order_by('-pub_date')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Land of Lei{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <img class="img-responsive", src="../media/bannner.jpg">



</head>
<body>
<div id="wrapper">
    <nav class="navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
                <a class="navbar-brand" href="{% url 'blog:index' %}">Land of Lei</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id ="topNavBar">
            <ul class="nav navbar-nav">
                <li class={% block projects %}""{% endblock %}>
                    <a href="{% url 'projects:index' %}">
                        <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>&nbsp; Projects
                    </a>
                </li>
                <li class={% block publication %}""{% endblock %}>
                    <a href="{% url 'publications:index' %}">
                        <span class="glyphicon glyphicon-file" aria-hidden="true"></span>&nbsp; Publications
                    </a>
                </li>
                <li class={% block members %}""{% endblock %}>
                    <a href="{% url 'members:index' %}">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Members
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% block body%}
{% endblock %}
</div>
</body>
</html>

templates/blog/index.html
{% extends 'base.html' %}

{% block title %}Land of Lei{% endblock %}

{% block body %}
    {% for post in object_list %}
        <img src="{{ project.picture.url }}" class="img-responsive">
        <h5>{{ post.published_date|date:"Y-m-d" }}</h5>
        <h4><a href="/blog/{{ post.id }}"> "{{ post.title }}"</a></h4>
        <p>{{ post.text }}</p>
    {% endfor %}
{% endblock %}

templates/blog/post.html
{% extends 'base.html' %}

{% block title %}Land of Lei{% endblock %}

{% block body %}
    {% for post in object_list %}
        <img src="{{ project.picture.url }}" class="img-responsive">
        <h3><a href="/blog/{{ post.id }}"> {{ post.title }}</a></h3>
        <h5>{{ post.published_date|date:"Y-m-d" }}</h5>
        {{ post.text|safe|linebreaks }}
    {% endfor %}
{% endblock %}

templates/members/index.html
{% extends 'base.html' %}

{% block title %}Members{% endblock %}
{% block members %}"active"{% endblock %}

{% block body %}

    <img src="../../media/lei.jpg" class="img-responsive">
    <h4>Xin Gen Lei</h4>
    <I>Professor</I>
    <li>Cornell University</li>
    <li>Department of Animal Science</li>
    <li>507 Tower Road Ithaca, NY 14850</li>
    <li>email: xl20@cornell.edu</li>
    <li>phone: (607)254-4703</li>

    <h2>Current members:</h2>
    {% for member in object_list %}
        {% if not member.end_date %}
            <img src="{{ member.picture.url }}" class="img-responsive", width="300", height="400">
            <h4>{{ member.first_name }} {{ member.last_name }}</h4>
            <I>{{ member.position }}</I>
            <li>{{ member.start_date.month }}/{{ member.start_date.year }} - Present</li>
            <li>Research interests: {{ member.research_interests }}</li>
        {% endif %}
    {% endfor %}
    <h2>Past members:</h2>
    {% for member in object_list %}
        {% if member.end_date %}
            <img src="{{ member.picture.url }}" class="img-responsive", width="300", height="400">
            <h4>{{ member.first_name }} {{ member.last_name }}</h4>
            <I>{{ member.position }}</I>
            <li>Current employer: {{ member.new_employer }}</li>
            <li>{{ member.start_date.month }}/{{ member.start_date.year }} -
                {{ member.end_date.month }}/{{ member.end_date.year }}</li>
            <li>Research interests: {{ member.research_interests }}</li>
        {% endif %}
    {% endfor %}
{% endblock %}

templates/projects/index.html
{% extends 'base.html' %}

{% block title %}Projects{% endblock %}
{% block projects %}"active"{% endblock %}

{% block body %}
    <h3>Current projects:</h3>
    {% for project in all_projects %}
        <div class="row">
            <div class="col-xs-12 col-sm-5">
                <img src="{{ project.picture.url }}" class="img-responsive" width="400">
            </div>
            <div class="col-xs-12 col-sm-7">
                <div class="row">
                    <div class="col-sm-11">
                        <h2>{{ project.title }}</h2>
                    </div>
                </div>
            </div>
                <p>{{ project.description }}</p>
                <h6><strong>project funded by: {{ project.funding }}</strong></h6></div>
        <div class="col-xs-12">
            <hr />
        </div>
        </div>
    {% endfor %}
{% endblock %}

templates/publications/index.html
{% extends 'base.html' %}

{% block title %}Publications{% endblock %}
{% block publication %}"active"{% endblock %}

{% block body %}
    <ol>
        {% for publication in object_list %}
            <li>{{ publication.citation }}</li>
        {% endfor %}
    </ol>
{% endblock %}